/**
 * Writes crates/pob-engine/lua/mod_families.lua: for each PoB mod group whose
 * game family is shared with another group, the families it belongs to. The
 * game rolls one mod per family; PoB's group is only the mod type.
 *
 *   bun scripts/mod-families.ts --poe2 S:/POE2-Extracted/4.5.5.3-stripped --poe1 S:/POE1-Extracted/3.29.3.3-stripped
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const args = process.argv.slice(2);
function arg(name: string): string {
  const i = args.indexOf(`--${name}`);
  if (i < 0 || !args[i + 1]) throw new Error(`missing --${name} <export dir>`);
  return args[i + 1];
}

const LINE = /^\s*\["([^"]+)"\] = \{ type = "(?:Prefix|Suffix)",.*?\bgroup = "([^"]*)"/;

function familiesFor(pobRoot: string, exportDir: string): [string, string[]][] {
  const mods: Record<string, { groups?: string[] }> = JSON.parse(readFileSync(join(exportDir, "mods.json"), "utf8"));
  const byGroup = new Map<string, Set<string>>();
  let missing = 0;
  const dataDir = join(pobRoot, "Data");
  for (const file of readdirSync(dataDir).filter((f) => /^Mod.*\.lua$/.test(f))) {
    for (const line of readFileSync(join(dataDir, file), "utf8").split("\n")) {
      const m = LINE.exec(line);
      if (!m) continue;
      const [, id, group] = m;
      const fams = mods[id]?.groups;
      if (!fams) {
        missing++;
        continue;
      }
      if (!byGroup.has(group)) byGroup.set(group, new Set());
      for (const f of fams) byGroup.get(group)!.add(f);
    }
  }
  const groupsPerFamily = new Map<string, number>();
  for (const fams of byGroup.values()) for (const f of fams) groupsPerFamily.set(f, (groupsPerFamily.get(f) ?? 0) + 1);
  const out = [...byGroup]
    .filter(([, fams]) => fams.size > 1 || [...fams].some((f) => groupsPerFamily.get(f)! > 1))
    .map(([g, fams]) => [g, [...fams].sort()] as [string, string[]])
    .sort((a, b) => (a[0] < b[0] ? -1 : 1));
  console.log(`${pobRoot}: ${byGroup.size} groups, ${out.length} share a family, ${missing} mods not in the export`);
  return out;
}

function lua(entries: [string, string[]][]): string {
  return entries.map(([g, fams]) => `\t\t["${g}"] = { ${fams.map((f) => `"${f}"`).join(", ")} },`).join("\n");
}

const poe2 = familiesFor("src-tauri/resources/pob", arg("poe2"));
const poe1 = familiesFor("src-tauri/resources/pob1", arg("poe1"));
const text = `-- Generated by scripts/mod-families.ts; do not edit.\nreturn {\n\tpoe2 = {\n${lua(poe2)}\n\t},\n\tpoe1 = {\n${lua(poe1)}\n\t},\n}\n`;
writeFileSync("crates/pob-engine/lua/mod_families.lua", text.replace(/\n/g, "\r\n"));
